baseURL = 'https://palladiumred.netlify.app/'
languageCode = 'en-us'
title = 'Tech Palladin'
theme = 'ananke'


SectionPagesMenu = "main"
Paginate = 5                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""


[params]
text_color = ""
author = "Tech Palladin"
favicon = ""
site_logo = "images/site-logo.webp"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3